server:
  port: 10010

spring:
  application:
    name: del-gateway
  profiles:
    active: dev
  security:
    enabled: false
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: sakana
      config:
        server-addr: 127.0.0.1:8848
        namespace: sakana
        group: DEFAULT_GROUP
        file-extension: yml
    gateway:
      # 网关路由配置（迁移到 del-gateway.yml）
      routes: []
  config:
    import:
      - optional:nacos:common-jwt.yml
      - optional:nacos:common-actuator.yml
      - optional:nacos:del-gateway.yml

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always
