server:
  port: 10003


spring:
  application:
    name: gateway
    profiles:
      active: dev

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: sakana

      config:
        server-addr: localhost:8848
        namespace: sakana
        group: DEFAULT_GROUP
        file-extension: yml
        import-check:
          enabled: false
    gateway:
      metrics:
        enabled: true
      routes:            # routes 决定“请求怎么走”    http://localhost:10003/cloudIdGenerator/id
        - id: cloudIdGenerator
          uri: lb://cloudIdGenerator  # 通过LoadBalancer寻找user-service实例，而不是从Nacos注册中心获取
          predicates:    # predicates 决定“请求是不是走这条路”
            - Path=/cloudIdGenerator/**  # htt
          filters:       # StripPrefix 决定“请求走这条路之前把路径砍掉多少层” http://cloudIdGenerator/id  通过服务名调用服务
            - StripPrefix=1

#  config:
#    import:
#      - optional:nacos:gateway-dev.yml



management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: health,info
        base-path: /actuator
  endpoint:
    health:
      show-details: always
    env:
      enabled: true

  prometheus:
    metrics:
      export:
        enabled: true


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG
    org.springframework.cloud.gateway.filter: DEBUG
    reactor.netty: DEBUG