spring:
  application:
    name: cloudIdGenerator
  profiles:
    active: dev

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: sakana

      config:
        server-addr: localhost:8848
        namespace: sakana
        group: DEFAULT_GROUP
        file-extension: yml
        import-check:
          enabled: false




      # 继承上方公共配置，无需单独指定 server-addr

  config:
    import:
      - optional:nacos:actuator-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}?group=DEFAULT_GROUP&refreshEnabled=true

snowflake:
  datacenter-id: 1

---
spring:
  config:
    activate:
      on-profile: dev

server:
  port: 9802

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

---
spring:
  config:
    activate:
      on-profile: prod

server:
  port: 9801

#management:
#  endpoints:
#    web:
#      base-path: /my-actuator
#      exposure:
#        include: health,info,metrics,beans,env,configprops,loggers,threaddump,prometheus
#  endpoint:
#    health:
#      show-details: always
#      show-components: always
#    metrics:
#      enabled: true
#    prometheus:
#      enabled: true
#    shutdown:
#      enabled: true
#    loggers:
#      enabled: true